version: '3.8'

services:
  postgres:
    container_name: postgres
    hostname: database.local
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: storage
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    hostname: redis.local
    image: redis:7.4.0
    ports:
      - "6379:6379"

  minio:
    container_name: minio
    image: bitnami/minio:2024.7.26
    restart: always
    hostname: minio.local
    volumes:
      - ./minio:/bitnami/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root
      MINIO_ACCESS_KEY: QorF6XbT8Rs6FeHRkLaH
      MINIO_SECRET_KEY: phiqSNaAiNjxXL4N24h9ZjKYIO0XTyIeQkkUEEN7

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio